apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: keycloak
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.2
          args: ["start", "--cache-stack=kubernetes"]
          volumeMounts:
            - name: certs
              mountPath: "/etc/certs"
              readOnly: true
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                {
                  secretKeyRef:
                    { name: keycloak-secret, key: KEYCLOAK_ADMIN_USERNAME },
                }

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                {
                  secretKeyRef:
                    { name: keycloak-secret, key: KEYCLOAK_ADMIN_PASSWORD },
                }
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/certs/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/certs/tls.key"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: auth.localtest.me
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                { secretKeyRef: { name: keycloak-secret, key: DB_URL } }

            - name: KC_DB_USERNAME
              valueFrom:
                { secretKeyRef: { name: keycloak-secret, key: DB_USERNAME } }

            - name: KC_DB_PASSWORD
              valueFrom:
                { secretKeyRef: { name: keycloak-secret, key: DB_PASSWORD } }

            - name: jgroups.dns.query
              value: keycloak
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          ports:
            - name: jgroups
              containerPort: 7600
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health/ready
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: certs
          secret:
            secretName: auth-tls-secret
